app/__init__.py
"""
/app

configure app/ with config.py
"""

from flask import Flask
from flask_bootstrap import Bootstrap
from flask_moment import Moment
from config import config

# initialize objects
moment = Moment()
bootstrap = Bootstrap()


# create application
def create_app(config_name):
    app = Flask(__name__)
    # run additional init_app from Config class
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    # initialize objects with config.py
    bootstrap.init_app(app)
    moment.init_app(app)

    # call Blueprint from main/
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    # redirect requests to secure HTTP
    # enable only in production mode
    if not app.debug and not app.testing and not app.config['SSL_DISABLE']:
        from flask_sslify import SSLify
        sslify = SSLify(app)

    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, datajkt, scrapejkt

app/main/views.py
"""
views.py

url routing to '/', '/admin', '/content'
"""

from flask import render_template, session, redirect, url_for, abort, current_app, flash, request
from datetime import datetime
from flask_moment import Moment

from . import main
from .datajkt import updateJKTAPI
from .scrapejkt import updateJKTBlog, updateJKTEvents

@main.route('/')
def index():
    return redirect(url_for(".content"))

@main.route('/admin')
def admin():
    return render_template('admin.html',
                            time=datetime.utcnow())


@main.route('/content')
def content():
    # call jakarta api
    cctv = updateJKTAPI()

    # scrape smartcity.jakarta.go.id news and events
    newsList = updateJKTBlog()
    eventsList = updateJKTEvents()

    # call iframe jakarta api html
    return render_template('content.html',
                            cctv=cctv,
                            newsList=newsList,
                            eventsList=eventsList)

@main.route('/content/puskesmas')
def jkt_puskesmas():
    return render_template('puskesmas_jkt.html')

app/templates/admin.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Alva Energi{% endblock %}

{% block page_content %}
    <div class="page-header">
      <h1>Solar PV Monitoring System - Admin</h1>
    </div>
    <div class="col-md-4">
      <h3>Pulau Geranting, Indonesia</h3>
        <iframe src="https://www.openstreetmap.org/export/embed.html?bbox=103.64604949951173%2C0.8730359780906259%2C103.88946533203126%2C1.074193962329908&amp;layer=mapnik&amp;marker=0.9736164704784636%2C103.76775741577148"></iframe>
    </div>
    <div class="col-md-4">
      <iframe src="https://data.sparkfun.com/solar_geranting" height="400" width="500"></iframe>
    </div>
{% endblock %}

app/templates/base.html
{% extends "bootstrap/base.html" %}

{% block head %}
  {{ super() }}
  <link rel="stylesheet" href="{{ url_for('static', filename = 'styles.css') }}" />
  <link rel="icon" href="{{ url_for('static', filename='images/alva.png') }}" type="image/x-icon">
{% endblock %}

{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="http://www.alvaenergi.com">Alva Energi</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{{ url_for('main.admin') }}">Admin</a></li>
                <li><a href="{{ url_for('main.content') }}">Content</a></li>
            </ul>
        </div>
    </div>
</div>
{% endblock %}


{% block content %}
  <div class="container">
    {% for message in get_flashed_messages() %}
      <div class ="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
      </div>
    {% endfor %}
    {% block page_content %}{% endblock %}
  </div>
{% endblock %}

{% block scripts %}
  {{ super() }}
{% endblock %}

app/templates/content.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Alva Energi{% endblock %}

{% block page_content %}
    <div class="page-header">
      <h1>Real-Time Data Streaming from Jakarta OpenAPI</h1>
    </div>
    <div class="post-tabs">
        <h3>Location of All Puskesmas in Jakarta</h3>
        <iframe src="{{ url_for('main.jkt_puskesmas') }}" height="400" width="500"></iframe>
    </div>
    <div class="post-tabs">
        <h3>Latest News from Jakarta Smart City</h3>
        {% for news in newsList %}
          <li><a href={{ news.url }}>{{ news.title }}</a></li>
        {% endfor %}
    </div>
    <div class="post-tabs">
        <h3>Latest Events from Jakarta Smart City</h3>
        {% for events in eventsList %}
          <li><a href={{ events.url }}>{{ events.title }}</a></li>
        {% endfor %}
    </div>
    <div class="post-tabs">
        <h3>Live CCTV from {{ cctv.name }}</h3>
        <iframe src="{{ cctv.url }}" height="400" width="500"></iframe>
    </div>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Alva Energi{% endblock %}

{% block page_content %}
    <div class="page-header">
      <h1>Solar PV Monitoring System - Admin</h1>
    </div>
    <div class="col-md-4">
      <h3>Pulau Geranting, Indonesia</h3>
        <iframe src="https://www.openstreetmap.org/export/embed.html?bbox=103.64604949951173%2C0.8730359780906259%2C103.88946533203126%2C1.074193962329908&amp;layer=mapnik&amp;marker=0.9736164704784636%2C103.76775741577148"></iframe>
    </div>
    <div class="col-md-4">
      <iframe src="https://data.sparkfun.com/solar_geranting" height="400" width="500"></iframe>
    </div>
{% endblock %}